name: analyze
on: [push]
jobs:
  build:
    runs-on: rtx6000-4x
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          cd lib && ./configure --enable-sm80 --disable-openmp && cd ..
      - name: analyze
        run: |
          cd lib && scan-build -o ../_analyze --use-cc clang make
      - name: upload report
        run: |
          cd _analyze
          FILE=$(ls)
          mv $FILE /var/public_html/analyze/$FILE
          echo "View [$FILE](https://ci.libccv.org/analyze/$FILE)" >> $GITHUB_STEP_SUMMARY
