name: ubsan-unit-tests
on: [push]
jobs:
  build:
    runs-on: rtx6000-4x
    steps:
      - uses: actions/checkout@v2
      - name: configure & build
        run: |
          cd lib && ./configure --enable-sm80 && cd ..
          make -j 64 -C test COVER=1 all.tests
      - name: tests
        run: |
          make -C test check
      - name: coverage report
        run: |
          cd test && ./cover-gen.rb ../_coverage
