name: coverage
on:
  push:
    branches:
      - unstable
jobs:
  build:
    runs-on: rtx6000-4x
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure & build
        run: |
          cd lib && ./configure --enable-sm80 && cd ..
          make -j 64 -C test COVER=1 all.tests
      - name: tests
        run: |
          make -C test check
      - name: generate report
        run: |
          cd test && ./cover-gen.rb ../_coverage
      - name: upload report
        run: |
          cd _coverage
          FILE=$(ls)
          chmod -R go+rX $FILE
          mv $FILE /var/www/public_html/coverage/$FILE
          echo "View [$FILE](https://ci.libccv.org/coverage/$FILE)" >> $GITHUB_STEP_SUMMARY
