name: cuda-int-tests
on:
  push:
    branches:
      - unstable
jobs:
  build:
    runs-on: rtx6000-4x
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure & build
        run: |
          cd lib && ./configure --enable-sm80 && cd ..
          make -j 32 -C test/int/nnc
      - name: integration tests
        run: |
          make -C test/int/nnc test
