name: ubsan-unit-tests
on:
  push:
    branches:
      - unstable
jobs:
  build:
    runs-on: rtx6000-4x
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure & build
        run: |
          cd lib && ./configure --enable-sm80 && cd ..
          make -j 32 -C lib ubsan
          make -j 32 -C bin ubsan
          make -j 32 -C bin/nnc ubsan
          make -j 32 -C bin/cuda ubsan
          make -j 32 -C test ubsan
      - name: tests
        run: |
          make -C test test
